### PR TITLE
Add dot

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by mattn** [comment]
@Getty Hi, I want to transfer this module into marcel-mainte org. This module is created by Marcel, and he made me co-mainte (without my agreements, maybe it was joke). How to transfer this module into there?

**Comment by Getty** [comment]
Oh sure, I am very far away from that module, why you ask me? :)

**Comment by mattn** [comment]
Because I found your account in http://marcel-maint.github.io/

**Comment by Getty** [comment]
Oh oh, now i get it, sorry, was not fully grasping the situation, yeah sure, I can add you to the organization and you can just help, sure, mompls

**Comment by Getty** [comment]
done

**Comment by mattn** [comment]
Thanks your work. I only want to give up this module.

**Comment by mattn** [comment]
Can I push this module into https://github.com/marcel-maint/Module-Install-ReadmeMarkdownFromPod ?

**Comment by Getty** [comment]
that is why i created it, would be nice if you would make at least one last release with the new URLs in the meta information, so that we can later care about the overtake if someone actually needs to overtake it (so that he doesn't search it at your git anymore)

**Comment by mattn** [comment]
I don't have motivation to keep developing this module any more. If you will merge my latest change into your repo, I will remove my repo. And I want to give up primary mainte (also co-mainte).

**Comment by Getty** [comment]
You dont need to keep developing, just keep the maint still someone can take over (like the next guy who wants a change to it, you just dispatch over). Would be harsh to just drop it off to us, we are also victims ;)

**Comment by mattn** [comment]
Oh, I already removed my permition on pause.

**Comment by Getty** [comment]
<headache>

**Pull request merged**
